(() => {
  "use strict";

  const translations = {
    en: {
      metaDescription: "Calculate the finish-timer setting for supported Samsung and Bosch washing machines.",
      homeLabel: "Laundry Window home", languageLabel: "Language", englishLabel: "English (UK)", dutchLabel: "Dutch", marketDayLabel: "Choose whether to optimise for today or tomorrow",
      heroEyebrow: "CHEAP-ENERGY WASH PLANNER", heroTitle: "Set the time.<br>Skip the maths.", heroIntro: "Tell me when electricity is cheap, which machine you use and what you’re washing. I’ll tell you exactly what to select on its <strong>finish timer</strong>.",
      plannerLabel: "Washing-machine finish-timer calculator", programHeading: "Machine & washing programme", programIntro: "Model-specific baseline times, with your choices remembered locally.", machineLabel: "Washing machine", programLabel: "Programme",
      windowHeading: "Cheap energy window", windowIntro: "Enter it yourself or ask for the cheapest available fit.", starts: "Starts", ends: "Ends", manualWindow: "Manual cheap-energy window.", marketWindow: "Suggested low-price band from exact 15-minute market intervals. The {margin}-minute safety margin is applied inside it.",
      marketEyebrow: "DUTCH DAY-AHEAD PRICES", marketHeading: "Find the cheapest fit", marketIntro: "Compares every valid finish-timer setting for this programme.", suggestToday: "Suggest today", suggestTomorrow: "Suggest tomorrow", checking: "Checking…", marketDefault: "The shown price is the raw wholesale market price, excluding all taxes, fees, supplier markups and other additions. Fetched only when you ask.", marketSource: "Source: <a href=\"https://consumenten.energyzero.nl/actuele-tarieven\" rel=\"noreferrer\">EnergyZero</a> public API.",
      fineTune: "Fine-tune", tuneHeading: "Make it match your machine", tuneIntro: "Optional—defaults already work.", settingAt: "Setting the machine at", now: "Now", measured: "Your measured programme time", savedDevice: "Saved on this device.", margin: "Edge safety margin", noMargin: "No margin", minutes: "{count} minutes", addPrewash: "Add prewash", prewashNote: "Samsung says this adds about 18 minutes.",
      selectMachine: "SELECT ON THE MACHINE", readyHeading: "Ready when you are", readyText: "Choose a valid window to see the finish-timer setting.",
      whyEyebrow: "WHY THIS NUMBER?", whyTitle: "The button chooses when the wash <em>ends</em>.", why1: "Starting now needs no timer; {timer} accepts whole-hour settings from <strong>{min} to {max} hours</strong>.", why2: "We subtract the programme time to check that the wash <strong>starts after cheap energy begins</strong>.", why3: "We centre the cycle in the window where possible, leaving room for <strong>real-world timing drift</strong>.",
      reference: "Programme-time reference", samsungManualPage: "Samsung manual · page 37", samsungReferenceText: "Official Samsung baseline durations. Quick wash can be selected at 15, 20, 30, 40, 50 or 60 minutes. Actual times can vary with water pressure and temperature, load, fabric and selected options. <a class=\"source-link\" href=\"https://www.samsung.com/nl/support/model.WF702Y4BKWQ_EN/\" rel=\"noreferrer\">Official Samsung support page</a>.", boschManualPage: "Bosch WAE284A7 / Maxx 7 programme table", boschReferenceText: "Documented baseline/test settings for this Bosch profile. The manual says programme duration can change as the wash is optimised, and it does not publish one fixed duration for every dial programme. Use the measured-time field for a displayed duration that differs. <a class=\"source-link\" href=\"https://www.bosch-home.nl/nl/productservice/WAE284A7NL-12\" rel=\"noreferrer\">Official Bosch model page</a>.",
      compatibility: "COMPATIBILITY", compatibilityTitle: "Two model profiles.<br><em>More machines later.</em>", compatibilityIntro: "Each profile has its own programme baselines and finish-timer range. Choose the exact model before planning.", verified: "PHYSICALLY VERIFIED", exactMachine: "The exact Samsung used to create and check the original calculator.", sameManual: "SAME SAMSUNG MANUAL", familyText: "Y4BK and B4BK families are covered by the same official programme table. Regional suffixes may differ.", boschProfile: "MODEL PROFILE", boschFamilyText: "Documented baseline settings and the 1–24 hour Klaar in range. Adaptive programmes use the measured-time override.", footerText: "Made for specific washing machines—and one less piece of mental arithmetic.", githubRepo: "View source on GitHub",
      samsungMachineOption: "Samsung WF702Y4BKWQ/EN (WF/600–702 Y4BK/B4BK)", boschMachineOption: "Bosch WAE284A7NL/12 (Maxx 7 VarioPerfect)", samsungTimerName: "Delay End", boschTimerName: "Ready in",
      dialGroup: "Dial programmes", quickGroup: "Quick wash button", boschCottonGroup: "Cotton settings", boschOtherGroup: "Other documented settings", cotton: "Cotton", synthetics: "Synthetics", jeans: "Jeans", bedding: "Bedding", dark: "Dark garments", daily: "Daily wash", drum: "Eco drum clean", baby: "Baby care", sports: "Outdoor care", hand: "Hand wash", wool: "Wool", quick: "Quick wash", boschCotton20: "Cotton 20 °C", boschCotton30: "Cotton 30 °C", boschCotton40: "Cotton 40 °C", boschCotton60: "Cotton 60 °C", boschCotton90: "Cotton 90 °C", boschEasyCare40: "Easy-care 40 °C", boschQuickMix40: "Quick/Mix 40 °C", boschDelicates30: "Delicates/Silk 30 °C", boschWool30: "Wool 30 °C", boschSuperQuick15: "Super quick 15′",
      durationMin: "{minutes} min", durationHour: "{hours} hr", durationHoursMinutes: "{hours} hr {minutes} min", savedFor: "Saved on this device for {program}.", preferredInBrowser: "Preferred in this browser: {program}.", preferred: "Preferred", makePreferred: "Make selected preferred",
      settingsChanged: "The settings changed. Ask again to recalculate the cheapest fit.", invalidPlanning: "Choose a valid machine-setting time first.", fetching: "Fetching the latest published Dutch day-ahead prices…", noDayFit: "No complete wash fits {day} using Start now or the machine’s {min}–{max} hour {timer} range.", tomorrowUnavailable: "Tomorrow’s prices are not available from EnergyZero yet. They are normally published around 15:00; please try again later.", marketSuccess: "Low-price band for {day}: {lowStart}–{lowEnd}. Best selectable wash for {program}: {start}–{end} ({percent}% in the band). {deadline} Raw wholesale price: {price} ct/kWh, excluding all taxes, fees, markups and other additions. Prices available through {available}.", startDeadline: "Start by {deadline} to keep the complete wash and {margin}-minute safety margin inside the low-price band.", startDeadlinePassed: "The {deadline} safe-start deadline has passed.", marketError: "Live prices could not be loaded. Manual window entry still works; please try the suggestion again later.", today: "today", tomorrow: "tomorrow",
      invalidDate: "Choose a valid date and time.", invalidWindow: "The cheap-price end must be after its start.", noWholeFit: "No whole-hour {timer} setting keeps this complete cycle inside the window.", tooLong: "This programme is longer than the cheap-price window (including your margin).", tooEarly: "This window ends before the machine’s minimum {min}-hour timer setting.", tooLate: "This window starts beyond the machine’s {max}-hour timer limit.", safetyMessage: "The complete wash fits inside the displayed window, but the requested {margin}-minute safety margin is short by {used} minutes.", safetyTitle: "Fits window · safety margin short by {shortfall} min", closestTitle: "Closest fit · {percent}% on cheap energy",
      checkWindow: "Check the window", instruction: "Press <strong>{timer}</strong> until the display shows <strong id=\"delay-inline\"></strong>, then press Start/Pause.", instructionNow: "Do not set the <strong>finish timer</strong>. Press Start/Pause now.", startNowHeading: "Start now", nowReadout: "NOW", expectedTiming: "Expected wash timing", washStarts: "WASH STARTS", washEnds: "WASH ENDS", plannedDuration: "Planned duration", windowSummary: "Cheap window", marketBandSummary: "Market low-price band", refresh: "Refresh “now” before setting the machine"
    },
    nl: {
      metaDescription: "Bereken de eindtimerinstelling voor ondersteunde Samsung- en Bosch-wasmachines.",
      homeLabel: "Laundry Window startpagina", languageLabel: "Taal", englishLabel: "Engels (VK)", dutchLabel: "Nederlands", marketDayLabel: "Kies of je voor vandaag of morgen wilt optimaliseren",
      heroEyebrow: "WASPLANNER VOOR GOEDKOPE STROOM", heroTitle: "Stel de tijd in.<br>Sla het rekenen over.", heroIntro: "Vertel wanneer stroom goedkoop is, welke machine je gebruikt en welk programma je kiest. Ik vertel precies wat je bij de <strong>eindtimer</strong> moet instellen.",
      plannerLabel: "Calculator voor de eindtimer van de wasmachine", programHeading: "Machine en wasprogramma", programIntro: "Modelgebonden basistijden, met je keuzes lokaal onthouden.", machineLabel: "Wasmachine", programLabel: "Programma",
      windowHeading: "Goedkope-stroomvenster", windowIntro: "Vul het zelf in of laat het goedkoopste passende moment zoeken.", starts: "Begint", ends: "Eindigt", manualWindow: "Handmatig goedkoop stroomvenster.", marketWindow: "Voorgestelde lage-prijsperiode uit exacte marktkwartieren. De veiligheidsmarge van {margin} minuten wordt daarbinnen toegepast.",
      marketEyebrow: "NEDERLANDSE DAY-AHEADPRIJZEN", marketHeading: "Vind het goedkoopste moment", marketIntro: "Vergelijkt elke geldige eindtimerinstelling voor dit programma.", suggestToday: "Vandaag voorstellen", suggestTomorrow: "Morgen voorstellen", checking: "Controleren…", marketDefault: "De getoonde prijs is de kale beursprijs, exclusief alle belastingen, kosten, leveranciersopslagen en andere toevoegingen. Alleen opgehaald wanneer je erom vraagt.", marketSource: "Bron: openbare API van <a href=\"https://consumenten.energyzero.nl/actuele-tarieven\" rel=\"noreferrer\">EnergyZero</a>.",
      fineTune: "Fijn afstellen", tuneHeading: "Pas het aan jouw machine aan", tuneIntro: "Optioneel—de standaardwaarden werken al.", settingAt: "Machine instellen om", now: "Nu", measured: "Jouw gemeten programmaduur", savedDevice: "Op dit apparaat opgeslagen.", margin: "Veiligheidsmarge aan de rand", noMargin: "Geen marge", minutes: "{count} minuten", addPrewash: "Voorwas toevoegen", prewashNote: "Volgens Samsung duurt dit ongeveer 18 minuten extra.",
      selectMachine: "KIES OP DE MACHINE", readyHeading: "Klaar wanneer jij dat bent", readyText: "Kies een geldig venster om de eindtimerinstelling te zien.",
      whyEyebrow: "WAAROM DIT GETAL?", whyTitle: "De knop bepaalt wanneer de was <em>eindigt</em>.", why1: "Direct starten heeft geen timer nodig; {timer} accepteert hele uren van <strong>{min} tot en met {max} uur</strong>.", why2: "We trekken de programmaduur af om te controleren dat de was <strong>na het begin van de goedkope stroom start</strong>.", why3: "Waar mogelijk centreren we de was in het venster, met ruimte voor <strong>afwijkingen in de werkelijke duur</strong>.",
      reference: "Overzicht van programmatijden", samsungManualPage: "Samsung-handleiding · pagina 37", samsungReferenceText: "Officiële Samsung-basistijden. Kort programma kan worden ingesteld op 15, 20, 30, 40, 50 of 60 minuten. Werkelijke tijden kunnen variëren door waterdruk en -temperatuur, belading, textiel en gekozen opties. <a class=\"source-link\" href=\"https://www.samsung.com/nl/support/model.WF702Y4BKWQ_EN/\" rel=\"noreferrer\">Officiële Samsung-ondersteuningspagina</a>.", boschManualPage: "Bosch WAE284A7 / Maxx 7-programmatabel", boschReferenceText: "Gedocumenteerde basis-/testinstellingen voor dit Bosch-profiel. Volgens de handleiding kan de programmaduur tijdens de was veranderen door optimalisatie; bovendien is niet voor elk draaiknopprogramma één vaste duur gepubliceerd. Gebruik het veld voor gemeten tijd wanneer het display een andere duur toont. <a class=\"source-link\" href=\"https://www.bosch-home.nl/nl/productservice/WAE284A7NL-12\" rel=\"noreferrer\">Officiële Bosch-modelpagina</a>.",
      compatibility: "COMPATIBILITEIT", compatibilityTitle: "Twee modelprofielen.<br><em>Later meer machines.</em>", compatibilityIntro: "Elk profiel heeft eigen programmabasistijden en een eigen eindtimerbereik. Kies vóór het plannen het exacte model.", verified: "FYSIEK GECONTROLEERD", exactMachine: "De exacte Samsung waarmee de oorspronkelijke calculator is gemaakt en gecontroleerd.", sameManual: "DEZELFDE SAMSUNG-HANDLEIDING", familyText: "De Y4BK- en B4BK-families staan in dezelfde officiële programmatabel. Regionale achtervoegsels kunnen verschillen.", boschProfile: "MODELPROFIEL", boschFamilyText: "Gedocumenteerde basisinstellingen en het bereik van 1–24 uur voor Klaar in. Gebruik bij adaptieve programma’s de gemeten-tijdcorrectie.", footerText: "Gemaakt voor specifieke wasmachines—en één rekensom minder in je hoofd.", githubRepo: "Bekijk de broncode op GitHub",
      samsungMachineOption: "Samsung WF702Y4BKWQ/EN (WF/600–702 Y4BK/B4BK)", boschMachineOption: "Bosch WAE284A7NL/12 (Maxx 7 VarioPerfect)", samsungTimerName: "Uitgesteld einde", boschTimerName: "Klaar in",
      dialGroup: "Draaiknopprogramma's", quickGroup: "Knop Kort programma", boschCottonGroup: "Katoen-instellingen", boschOtherGroup: "Andere gedocumenteerde instellingen", cotton: "Katoen", synthetics: "Synthetisch", jeans: "Jeans", bedding: "Beddengoed", dark: "Donkere kleding", daily: "Dagelijkse was", drum: "Eco trommelreiniging", baby: "Babykleding", sports: "Outdoorkleding", hand: "Handwas", wool: "Wol", quick: "Kort programma", boschCotton20: "Katoen 20 °C", boschCotton30: "Katoen 30 °C", boschCotton40: "Katoen 40 °C", boschCotton60: "Katoen 60 °C", boschCotton90: "Katoen 90 °C", boschEasyCare40: "Kreukherstellend 40 °C", boschQuickMix40: "Snel/Mix 40 °C", boschDelicates30: "Fijn/Zijde 30 °C", boschWool30: "Wol 30 °C", boschSuperQuick15: "Extra snel 15′",
      durationMin: "{minutes} min", durationHour: "{hours} uur", durationHoursMinutes: "{hours} uur {minutes} min", savedFor: "Op dit apparaat opgeslagen voor {program}.", preferredInBrowser: "Voorkeur in deze browser: {program}.", preferred: "Voorkeur", makePreferred: "Maak selectie voorkeur",
      settingsChanged: "De instellingen zijn gewijzigd. Laat het goedkoopste moment opnieuw berekenen.", invalidPlanning: "Kies eerst een geldige tijd waarop je de machine instelt.", fetching: "De nieuwste Nederlandse day-aheadprijzen ophalen…", noDayFit: "Geen volledige was past {day} via Start nu of het bereik van {min}–{max} uur voor {timer}.", tomorrowUnavailable: "De prijzen voor morgen zijn nog niet beschikbaar bij EnergyZero. Ze verschijnen normaal rond 15:00; probeer het later opnieuw.", marketSuccess: "De lage-prijsperiode voor {day} is {lowStart}–{lowEnd}. Beste instelbare was met {program}: {start}–{end} ({percent}% binnen de periode). {deadline} Kale beursprijs: {price} ct/kWh, exclusief alle belastingen, kosten, opslagen en andere toevoegingen. Prijzen beschikbaar tot {available}.", startDeadline: "Start uiterlijk om {deadline} om de volledige was én {margin} minuten veiligheidsmarge binnen de lage-prijsperiode te houden.", startDeadlinePassed: "De veilige starttijd van {deadline} is verstreken.", marketError: "Live prijzen konden niet worden geladen. Handmatig invoeren blijft werken; probeer het later opnieuw.", today: "vandaag", tomorrow: "morgen",
      invalidDate: "Kies een geldige datum en tijd.", invalidWindow: "Het einde van het goedkope venster moet na het begin liggen.", noWholeFit: "Geen hele-ureninstelling voor {timer} houdt deze volledige was binnen het venster.", tooLong: "Dit programma duurt langer dan het goedkope venster (inclusief marge).", tooEarly: "Dit venster eindigt vóór de minimale timerinstelling van {min} uur.", tooLate: "Dit venster begint na de maximale timerinstelling van {max} uur.", safetyMessage: "De volledige was past in het getoonde venster, maar de gevraagde veiligheidsmarge van {margin} minuten komt {used} minuten tekort.", safetyTitle: "Past in venster · veiligheidsmarge {shortfall} min te kort", closestTitle: "Beste benadering · {percent}% op goedkope stroom",
      checkWindow: "Controleer het venster", instruction: "Druk op <strong>{timer}</strong> tot het display <strong id=\"delay-inline\"></strong> toont en druk daarna op Start/Pauze.", instructionNow: "Stel de <strong>eindtimer</strong> niet in. Druk nu op Start/Pauze.", startNowHeading: "Start nu", nowReadout: "NU", expectedTiming: "Verwachte wastijden", washStarts: "WAS START", washEnds: "WAS EINDIGT", plannedDuration: "Geplande duur", windowSummary: "Goedkoop venster", marketBandSummary: "Lage-prijsperiode", refresh: "Vernieuw ‘nu’ voordat je de machine instelt"
    }
  };

  let language = "en";
  try {
    const saved = localStorage.getItem("laundry-language");
    language = saved === "nl" || saved === "en" ? saved : (navigator.language.toLowerCase().startsWith("nl") ? "nl" : "en");
  } catch (_) {}
  const listeners = [];
  const t = (key, values = {}) => Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), translations[language][key] || translations.en[key] || key);

  function apply() {
    document.documentElement.lang = language;
    document.title = language === "nl" ? "Laundry Window · eindtimercalculator" : "Laundry Window · washing-machine finish timer";
    document.querySelector('meta[name="description"]').content = t("metaDescription");
    document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); });
    document.querySelectorAll("[data-i18n-html]").forEach((element) => { element.innerHTML = t(element.dataset.i18nHtml); });
    document.querySelectorAll("[data-i18n-aria]").forEach((element) => { element.setAttribute("aria-label", t(element.dataset.i18nAria)); });
    document.querySelectorAll("[data-language]").forEach((button) => {
      const active = button.dataset.language === language;
      button.classList.toggle("active", active);
      button.setAttribute("aria-pressed", String(active));
    });
  }

  function setLanguage(next) {
    if (!translations[next] || next === language) return;
    language = next;
    try { localStorage.setItem("laundry-language", language); } catch (_) {}
    apply();
    listeners.forEach((listener) => listener(language));
  }

  document.addEventListener("DOMContentLoaded", () => {
    document.querySelectorAll("[data-language]").forEach((button) => button.addEventListener("click", () => setLanguage(button.dataset.language)));
    apply();
  });

  const scope = typeof window === "undefined" ? globalThis : window;
  scope.LaundryI18n = { translations, t, apply, onChange: (listener) => listeners.push(listener), get language() { return language; } };
})();
